spring:
  datasource:
    url: jdbc:mysql://39.104.87.202:3306/qihui?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: app
    password: 3ubVZhav7CyiLIFN
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 1024
        max-wait: 10000
        max-idle: 200
        min-idle: 0
    password:

  #rabbit
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    host: 127.0.0.1


##日志级别这是logback的
#logging:
#  level:
#    root: info
#    com:
#      jjw:
#        springboot:
#          controller: debug
#logging.path = /var/tmp 会在这个目录中生成spring.log
#logging.file = xxx.log 会在项目的根目录下生成xxx.log
#如果两个都配置了只有file的生效

#加载所有的端点，默认只加载了info/healthy
qihui:
  jwt:
    pubKeyPath: F:\\key\\rsa.pub
    priKeyPath: F:\\key\\rsa.pri
    secret: jjwhenlovexl
    expire: 30  #分钟
