spring:
  datasource:
    url: jdbc:mysql://39.105.10.118:3306/jjw?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 1024
        max-wait: 10000
        max-idle: 200
        min-idle: 0
    password:

  #rabbit
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    host: 127.0.0.1
#mybatis
mybatis:
  mapper-locations: classpath:mapping/*.xml


#日志级别这是logback的
logging:
  level:
    root: info
    com:
      jjw:
        springboot:
          controller: debug
#logging.path = /var/tmp 会在这个目录中生成spring.log
#logging.file = xxx.log 会在项目的根目录下生成xxx.log
#如果两个都配置了只有file的生效

#加载所有的端点，默认只加载了info/healthy
